name: Github_Actions_Study

on:
  push:
    branches: ["main"]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: create-vite-env
        run: |
          chmod 777 -R front
          cat <<EOL > front/.env
          VITE_PORTONE_STOREID=${{secrets.VITE_PORTONE_STOREID}} # ÏÉÅÏ†êID
          VITE_PORTONE_API_KEY=${{secrets.VITE_PORTONE_API_KEY}}
          EOL
          cat front/.env

      - name: create-application-secret
        run: |
          chmod 777 -R back
          cat <<EOL > back/src/main/resources/application-secret.yml
          spring:
            config:
              activate:
                on-profile: secret
            
            datasource:
              driver-class-name: com.mysql.cj.jdbc.Driver
              url: jdbc:mysql://${{secrets.EC2_PBULIC_IP}}:3306/${{secrets.DATABASE_NAME}}
              username: ${{secrets.DATABASE_USERNAME}}
              password: ${{secrets.DATABASE_PASSWORD}}
            
            security:
              oauth2:
                client:
                  registration:
                    google:
                      client-id: ${{secrets.OAUTH2_ID_GOOGLE}}
                      client-secret: ${{secrets.OAUTH2_SECRET_GOOGLE}}
                    naver:
                      client-id: ${{secrets.OAUTH2_ID_NAVER}}
                      client-secret: ${{secrets.OAUTH2_SECRET_NAVER}}

            jwt:
              secret: ${{secrets.JWT_SECRET}}
            EOL
            cat back/src/main/resources/application-secret.yml
        
          - name: print-directory
            run: |
              ls -a front
              ls -a back/src/main/resources

          - name: ü§ñ DockerHub-LOGIN
          uses: docker/login-action@v3.4.0
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

          - name:  Build-And-Push-React-App
            run: |
              cd front
              docker build -t ${{secrets.DOCKER_USERNAME}}/mcdonald-react-app .
              docker push ${{secrets.DOCKER_USERNAME}}/mcdonald-react-app:latest
              
          - name:  Build-And-Push-Spring-App
            run: |
              cd back
              docker build -t ${{secrets.DOCKER_USERNAME}}/mcdonald-spring-app .
              docker push ${{secrets.DOCKER_USERNAME}}/mcdonald-spring-app:latest
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: appleboy/ssh-action@1.0.3
        with:
          host: ${{secrets.EC2_PUBLIC_IP}}
          usernasme: ubuntu
          key: ${{secrets.SSH_KEY}}
      - name: DOCKER-REACT-APP-PULL
    
